### PR TITLE
Meta origin get fix - issue #41

### PR DESCRIPTION
**Pull request by izderadicka**
Fixing issue #41 
Added type check to Origin.get module search loop plus couple of tests.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@izderadicka Thank you. In order to accept this, we would need you to do two things. First, please sign the CLA. There is a link in the checks section of this PR. Second, please remove all changes in the `dist` folder since those are generated by us during the release process.

**Comment by izderadicka** [comment]
OK will do,
I've signed CLA just  now (I guess you should update link to CLA 
CONTRIBUTING.md because it led me to other form - on google docs, which 
I accepted also)  - hope hope now its's ok.
I will remove changes in dist.
However I noticed that this change in dist/system/index.js
```
-        if (_key !== "default" && key !== "__esModule") 
_exportObj[_key] = _aureliaMetadata[_key];
+       if (_key !== "default" && _key !== "__esModule") 
_exportObj[_key] = _aureliaMetadata[_key];
```

the original file was reference to key in second part of if condition- 
however variable seem to be _key -  are you sure original version was 
correct?

I.

**Comment by EisenbergEffect** [comment]
Please ping this issue once the dist folder contents are removed from the commit.

**Comment by doktordirk** [comment]
@izderadicka you forgot to:
 @EisenbergEffect ping

**Comment by izderadicka** [comment]
@EisenbergEffect ping
Hope PR is fine now
@doktordirk
thanks for reminder

**Comment by EisenbergEffect** [comment]
Looks good. Thanks!

**Pull request merged**
