### PR TITLE
refactor: upgrade the build process, move to TS

### PR DESCRIPTION
**Pull request by bigopon**
- convert the existing code base to TS (src/tests)
- update dependencies: now runs with gulp 4 (and node 12+)
- upgrade build: now uses rollup to bundle, and deliver sourcemap
- upgrade the build process: now important parts of the release process should be able to be run independently, and remove all existing gulp tasks, inline all in `gulpfile.js`
- upgrade test setup: remove jspm, and uses karma itself to run tests, with the help of karma-typescript
- change the changelog: I couldn't work out why conventional changelog doesn't generate empty messages, so now change to generate all **valid** commit messages.

cc @josundt

### CODE REVIEW

**Review by 3cp — APPROVED** [review]
LGTM 👍🏻

**Comment by 3cp** [comment]
Remove jspm from README pls.

**Comment by bigopon** [comment]
@3cp thanks for catching that

**Comment by elitastic** [comment]
Is there any chance that this will be merged and released soon?

**Pull request merged**
