### PR TITLE
added a test to show annotations can be added by function

### PR DESCRIPTION
**Pull request by ahmedshuhel**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Unfortunately, I don't think I can take this PR. The problem lies with the metadata refactoring. While it does use nifty new ES6 features, there's a problem with how these compile. Using a `for...of` loop converts to a much slower iteration behavior. It probably wouldn't be an issue in application code, but in the core framework I need to keep things as fast as possible. Does that make sense?

**Comment by ahmedshuhel** [comment]
@EisenbergEffect Got it. I was also not sure about it. Plain for loop is much faster. I will change them to for loop again. Anything else?

**Comment by ahmedshuhel** [comment]
@EisenbergEffect I used `let` too. And the main reason is that I sort of like variable declaration closer to the usage which is not a good practice in javascript because of the hoisting behavior. Now that we have `let` in javascript, we can do that, right? I saw you favor variable declaration closer to usage in .NET/Caliburn etc. Should I not use `let` too?

**Comment by EisenbergEffect** [comment]
Let's not use `let` either because that transplier just has to convert that to a var anyway and I'd like to have those declared at the top of the function for JS purposes. It's one of those things that doesn't transpile exactly right.

**Comment by ahmedshuhel** [comment]
Got it. I probably got a little carried away. Refactoring may not be a good idea at this stage from me. Next time I will consult before doing anything. Thanks for patience.

**Comment by EisenbergEffect** [comment]
No worries :) I'm thankful that you are willing to contribute.

For ES6 I'm sticking with a pretty small subset at the moment, to ensure that the transpiler has efficient ES5 output. That includes mostly just modules, classes, string interpolation and arrow functions.

**Comment by EisenbergEffect** [comment]
I'm making some changes in annotations shortly. I'd be interested if you could rebase on the upcoming changes and submit a pr with the correct message format.

**Comment by ahmedshuhel** [comment]
I will do it. Is [this](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#commit) the message format?

**Comment by EisenbergEffect** [comment]
Yep. That's it. Thanks!

On Tue, Jan 6, 2015 at 3:26 AM, Shuhel Ahmed <notifications@github.com>
wrote:

> I will do it. Is this
> <https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#commit>
> the message format?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/metadata/pull/1#issuecomment-68838438>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by ahmedshuhel** [comment]
I am on it.

**Pull request closed without merging**
